LEANCLOUD_APP_ENV=development \
LEANCLOUD_APP_ID=NlQwJxKuRDsRoTvTChS9MjHs-gzGzoHsz \
LEANCLOUD_APP_KEY=c2qUx8tQHqFvh0nVVB8Xku8H \
LEANCLOUD_APP_MASTER_KEY=1lNDvY5vmyOiOVKTuaMErDf6 \
LEANCLOUD_APP_PORT=4000 \
mvn jetty:run
